all:
	gcc -o pthread_setaffinity_np_test pthread_setaffinity_np_test.c -lm -lpthread
	gcc -o pro_1 pro_1.c -lm -lpthread
	gcc -o pro_2 pro_2.c -lm -lpthread
	gcc -o pro_3 pro_3.c -lm -lpthread
clean:
	rm -f pthread_setaffinity_np_test pro_1 pro_2 pro_3 
